project:
  type: website
  output-dir: docs

website:
  title: "Dr. Mirko Brüggemann"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
        light: flatly
        dark: slate
    css: styles.css
    toc: true

editor: visual

